export enum Message {
	DECRYPTION_PARTS_EMPTY = "DECRYPTION_PARTS_EMPTY",
	DOMAIN_URL_EMPTY = "DOMAIN_URL_EMPTY",
	EMAIL_NOT_SENT = "EMAIL_NOT_SENT",
	FAILED_FIND_USER_FROM_SESSION_ID = "FAILED_FIND_USER_FROM_SESSION_ID",
	INVALID_THEME = "IVALID_THEME",
	MAGIC_LINK_DIFFERENT_DEVICE = "MAGIC_LINK_DIFFERENT_DEVICE",
	MAGIC_LINK_EMPTY = "MAGIC_LINK_EMPTY",
	MAGIC_LINK_EXPIRED = "MAGIC_LINK_EXPIRED",
	MAGIC_LINK_INVALID = "MAGIC_LINK_INVALID",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	USER_SESSION_DELETION_FAILED = "USER_SESSION_DELETION_FAILED",
}
