export enum Message {
	EMAIL_NOT_SENT = "EMAIL_NOT_SENT",
	EMAIL_UPDATED = "EMAIL_UPDATED",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	TOKEN_NOT_FOUND = "TOKEN_NOT_FOUND",
	USER_NOT_UPDATED = "USER_NOT_UPDATED",
	USER_VERIFIED = "USER_VERIFIED",
	VERIFY_ADDRESS = "VERIFY_ADDRESS",
}
